### ISSUE TITLE
docker login Succeeded, docker pull failed

### ISSUE THREAD

**Issue by liaolinrong** [docker/docker-credential-helpers#158]
I use pass
`docker login` Succeeded:
```
# docker login 
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username: liaolinrong
Password: 
Login Succeeded
```

but when `docker pull`, is error:
```
docker pull liaolinrong/centos:7.3.1611
Error response from daemon: pull access denied for liaolinrong/centos, repository does not exist or may require 'docker login'
```

os:
```
# cat /etc/redhat-release 
CentOS Linux release 7.5.1804 (Core)

 # uname -a
Linux VM_0_6_centos 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

docker version:
```
# docker -v
Docker version 18.09.7, build 2d0083d
```

**Comment by fttriquet** [comment]
I have been encountering the same issue for the past few days, I still can't figure out why.

**Comment by maxthomas** [comment]
does your GPG key have a passphrase?

if so, can you try doing this first:

```
export GPG_TTY=$(tty)
```

**Comment by maxthomas** [comment]
@liaolinrong you didn't log in to your private repo, you logged in to the public docker repo

**Comment by akazakou** [comment]
The same issue for me. @maxthomas workaround with
```
export GPG_TTY=$(tty)
```
not working on Ubuntu 18.04. It starts after my GPG key expired. I've updated it in pass configuration and removed all stored data, but it still login success, but can't pull images.

**Comment by allertec** [comment]
Have the same problem, the workaround works, but not in all cases which I need

**Comment by vindubeyama** [comment]
@allertec  Is there any workaround for this? I am facing the same issue and I have tried all the credsStore but nothing seems to be working. Login is success but pull fails.

**Comment by vindubeyama** [comment]
@fttriquet Did you figure out the solutions to this?

**Comment by allertec** [comment]
> 
> 
> @allertec Is there any workaround for this? I am facing the same issue and I have tried all the credsStore but nothing seems to be working. Login is success but pull fails.


@vindubeyama nope, there is no workaound yet, however I have been using version 6.3.3, maybe using some old one will work, as you can see that some people around the internet are actually using it fine.

For me the only workaround is to keep password as a environment variable, and then use it when pulling something :/

**Comment by maksokami** [comment]
Same issue for me on  19.03.5

**Comment by Anishmourya** [comment]
it worked for me after run apt-get update .

**Comment by pgronau** [comment]
Same issue here. Using gitlabs docker registry.

```
abc@server:~$ docker login registry.gitlab.company.tld/<user>/<project>/
Authenticating with existing credentials...
WARNING! Your password will be stored unencrypted in /home/abc/snap/docker/423/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
abc@server:~$ docker run registry.gitlab.company.tld/<user>/<project>/<container>:latest
Unable to find image 'registry.gitlab.company.tld/<user>/<project>/<container>:latest' locally
docker: Error response from daemon: pull access denied for registry.gitlab.company.tld/<user>/<project>/<container>, repository does not exist or may require 'docker login'.
See 'docker run --help'.
```

 Docker running on ubuntu:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
```

Running as snap. So just in case you need it:
```
services:
  docker.dockerd: simple, enabled, active
snap-id:      sLCsFAO8PKM5Z0fAKNszUOX0YASjQfeZ
tracking:     latest/stable
refresh-date: today at 13:39 UTC
installed:         18.09.9                 (423) 126MB -
```

**Comment by WhoAteDaCake** [comment]
This is still an active issue, it completely prevents us of using this provider

**Comment by scott-dunt** [comment]
Experiencing same - similar issue. Docker login to Gitlab registry works fine, push to same fails, Access Denied.  
The GitLab side error logs are saying: msg="error authorizing context: authorization token required"

Traced my issue to docker-credentials-helper  and 'pass' package.. I had installed them because of warning message;
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
WARNING! Your password will be stored unencrypted in /home/ubuntu/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

BUT with the credential helper installed, I cannot push to Gitlab registry.. 

When I disabled and removed "apt remove golang-docker-credential-helpers pass"  Now I can successfully push to the registry..  

Which makes me wonder if Docker version 19.03.2, build 6a30dfc  is storing the password in the credential helper, but its not retrieving it? 

Also tried this on Docker version 19.03.8, build afacb8b7f0  - same issue.

**Comment by leimao** [comment]
> export GPG_TTY=$(tty)

This trick works on my Ubuntu 18.04 LTS.

**Comment by farvashani** [comment]
Make sure to have enough private docker repository in your docker hub account.
it seems you can create an private image but you can not pull the image when you exceed the private repository limits.

**Comment by svdHero** [comment]
I have a similar issue as @scott-dunt . With docker-credentials-helpers and `pass` I can login successfully, but a subsequent push fails with: `unauthorized to access repository: my-test-project/foo, action: push:`.

This is when trying to access an on-premise [Harbor](https://goharbor.io/) container registry (no hub.docker.com). I first suspected Harbor and opened an Issue with them (https://github.com/goharbor/harbor/issues/13553), but then I noticed that once I uninstall `pass` and get rid of the credential helpers then everything worked fine and I could push.

What's the matter here?

**Comment by userneeds-ahe** [comment]
[This](https://github.com/docker/docker-credential-helpers/issues/102#issuecomment-388974092) solved it for me on ubuntu

**Comment by dekelmidlink** [comment]
I encounter the issue on Amazon Linux 2. Does someone have solution for it?

**Comment by dekelmidlink** [comment]
> I encounter the issue on Amazon Linux 2. Does someone have solution for it?

Ok I fixed it with uninstalling everything including docker (don't forget /etc/docker folder) removing all the associated data that harbor created and the reinstalling everything

**Comment by evakili** [comment]
> export GPG_TTY=$(tty)

This works for me.

**Comment by lntsmn** [comment]
FWIW, changing credentials to a new PAT did the trick for me.

**Comment by smallst** [comment]
same here. Docker version 20.10.21 cannot pull. but docker 20.10.17 can. Not sure what happens. login normally

**Comment by vijay-pandurangan** [comment]
I still get the same error on windows. even tried with PAT as well but not help

**Comment by smallst** [comment]
okay if someone meets this bug in WSL. try to remove `"credsStore": "desktop.exe"` line in your `.docker/config.json` in wsl. it makes sense.

**Comment by 0xbillw** [comment]
Similar issue. Docker login to private harbor registry works fine, but push encounter error: unauthorized.
I fixed this issue. The reason for my problem is not `pass` or `gpg2`, but `golang-docker-credential-helpers` (I had installed `docker-desktop` before, and then uninstalled it).

My environment:
* Ubuntu 22.04
* Docker-Engine 20.10.21

1. uninstall `golang-docker-credential-helpers` (the old `docker-credential-pass` version is 0.6.4)
2. build the new `docker-credential-pass` (the new version is 0.7.0)
3. copy `docker-credential-pass` to `/usr/local/bin/`

I noticed that the `golang-docker-credential-helpers` package includes two binaries: `docker-credential-pass`, `docker-credential-secretservice`.
I'm not sure if the real cause of the problem is a `docker-credential-pass` version issue, or a `docker-credential-secretservice` issue. Their functions seem to be the same, so why are there two programs with the same function? What is the role of `docker-credential-secretservice`? Is it only useful for `docker-desktop` programs?

**Comment by tsoftware-tedu** [comment]
#192

**Comment by cowlinator** [comment]
Here's how to check which credsStore you're using: `cat /root/.docker/config.json`.

If you're using `pass`, here's how to tell if your GPG key requires a password:

```
pass
pass show docker-credential-helpers/"<your_credential_hash>/username"
```

If it then prompts you for a password, your GPG key requires a password.

When using `docker pull`, the gpg2 private key management password prompt does not pop up correctly

**Comment by AlexandrMilko** [comment]
I had a problem that docker login succeeded, but accessing private repo failed.
For me worked: **uninstall completely Docker Engine** and then install it again.
`https://askubuntu.com/questions/935569/how-to-completely-uninstall-docker`
`https://docs.docker.com/desktop/uninstall/`

**Comment by Dovchik** [comment]
Still encountering the same issue with `Docker version 26.1.3, build b72abbb`

**Comment by MarviMcFly** [comment]
I strugled with a similar issue the past couple of hours. Login to Azure Container Registry (ACR) was sugessfull but the pull fails with:
`Error response from daemon: Head "....": unauthorized: {"errors":[{"code":"UNAUTHORIZED","message":"authentication required, visit https://aka.ms/acr/authorization for more information."}]}`

@cowlinator Pointed out the, at least for me, rigth way. In case there is a passphrase `pass show ...`and entering the passphrase made docker pull for me working.

I do not think from that point that it is a issue related to docker-credential-helpers - more to docker itself.

**Comment by cowlinator** [comment]
@dovchik, be aware that `sudo docker login` uses `/root/.docker/config.json` instead of `~/.docker/config.json`
